export default [
  { id: 1, word: "苹果 (píngguǒ)", englishWord: "apple", isOn: true },
  { id: 2, word: "香蕉 (xiāngjiāo)", englishWord: "banana", isOn: true },
  { id: 3, word: "汽车 (qìchē)", englishWord: "car", isOn: true },
  { id: 4, word: "狗 (gǒu)", englishWord: "dog", isOn: true },
  { id: 5, word: "大象 (dàxiàng)", englishWord: "elephant", isOn: true },
  { id: 6, word: "青蛙 (qīngwā)", englishWord: "frog", isOn: true },
  { id: 7, word: "葡萄 (pútao)", englishWord: "grape", isOn: true },
  { id: 8, word: "帽子 (màozi)", englishWord: "hat", isOn: true },
  { id: 9, word: "冰淇淋 (bīngqīlín)", englishWord: "ice cream", isOn: true },
  { id: 10, word: "果汁 (gu果汁 (guozhi)", englishWord: "juice", isOn: true },
  { id: 11, word: "风筝 (fēngzheng)", englishWord: "kite", isOn: true },
  { id: 12, word: "狮子 (shīzi)", englishWord: "lion", isOn: true },
  { id: 13, word: "猴子 (猴子 ( hóuzi)", englishWord: "monkey", isOn: true },
  { id: 14, word: "坚果 (jiānguǒ)", englishWord: "nut", isOn: true },
  { id: 15, word: "猫头鹰 (māotóuyīng)", englishWord: "owl", isOn: true },
  { id: 16, word: "企鹅 (qǐ'ē)", englishWord: "penguin", isOn: true },
  { id: 17, word: "被子 (bèizi)", englishWord: "quilt", isOn: true },  
  { id: 18, word: "兔子 (tùzi)", englishWord: "rabbit", isOn: true },
  { id: 19, word: "太阳 ( tàiyáng)", englishWord: "sun", isOn: true },
  { id: 20, word: "乌龟 (wūguī)", englishWord: "turtle", isOn: true },
  { id: 21, word: "雨伞 (yǔsǎn)", englishWord: "umbrella", isOn: true },
  { id: 22, word: "小提琴 (xiǎotídīng)", englishWord: "violin", isOn: true },
  { id: 23, word: "鲸鱼 (jīngyú)", englishWord: "whale", isOn: true },
  { id: 24, word: "木琴 (mùqín)", englishWord: "xylophone", isOn: true },  
  { id: 25, word: "酸奶 (suānní)", englishWord: "yogurt", isOn: true },  
  { id: 26, word: "斑马 (bānma)", englishWord: "zebra", isOn: true },
]